### ISSUE TITLE
Interpreting output loci file

### ISSUE THREAD

**Issue by ManonGros** [to-mi/bmagwa#1]
Hi,
I wanted to make sure I understood how to interpret the loci file : the numbers in the file are indices of the loci in the input gen file right? (starting with 0) That means that if I want to find the corresponding SNP, I have to take the line corresponding in the bim file (+1).

For instance, if I am interested in the loci called '2890', I can use this command to find the matching SNP : 
sed -n '2891p' myData.bim

Does it make sense?
Thanks for your help,
Marie

**Comment by to-mi** [comment]
Hi Marie,

Yes, the indexing in the output files starts at zero (and, of course, line numbering usually starts at 1, so "index+1" is needed in converting to line numbers) and the order of the SNPs should follow the order of the input files (in the bed file which should be the same as in the corresponding bim file).

I hope this answers your question. I'm happy to answer any further questions.

-Tomi

**Comment by ManonGros** [comment]
Thanks! (I don't have any other questions so far but I will keep it in mind)
Best wishes,
Marie
