### ISSUE TITLE
rename postprocess.py

### ISSUE THREAD

**Issue by timflutre** [to-mi/bmagwa#2]
Would it be possible to rename `postprocess.py` into `bmagwa_postprocess.py`? This way, it is easier to add it to the PATH without having the risk of having a synonym from another software.

Moreover, could you also add this line at the top of the file: `#!/usr/bin/env python`? (Or what is the reason not to do it?)

ps: I can propose a pull request if you want

**Comment by to-mi** [comment]
Thank you, your suggestions make sense. I made the changes.

**Comment by timflutre** [comment]
Thanks!
